#!/bin/sh

BINDIR="/opt/dassault-systemes/draftsight/bin"
BINARY="${BINDIR}/DraftSight.bin"

if [ "${LD_LIBRARY_PATH:+set}" = "set" ]
then
	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${BINDIR}:${BINDIR}/../lib"
else
	export LD_LIBRARY_PATH="${BINDIR}:${BINDIR}/../lib"
fi
export QT_PLUGIN_PATH="${BINDIR}:${BINDIR}/../plugins"

cd "${BINDIR}"
"${BINARY}" "$@"
