#!/bin/sh
for file in $(find /usr/local/layman/init6 -iname  \*.ebuild); do
	echo "${file}";
	cp "${file}" "${file}~";
	echo "`cat /usr/portage/header.txt`" > "${file}";
	echo "" >> "${file}";
	echo "`sed '1,4d' "${file}~"`" >> "${file}";
	rm -rf "${file}~";
	ebuild "${file}" digest;
done;

for file in $(find /usr/local/layman/init6 -iname  ChangeLog); do
	echo "${file}";
	cp "${file}" "${file}~";
	echo "`cat /usr/portage/header.txt`" > "${file}";
	echo "" >> "${file}";
	echo "`sed '1,4d' "${file}~"`" >> "${file}";
	rm -rf "${file}~";
done;