#!/bin/bash
# emerge in tmpfs
MEMSIZE=2048M
mounted=false

. /etc/init.d/functions.sh

mounttmpfs() {
                mount -t tmpfs -o size=$MEMSIZE,nr_inodes=1M tmpfs /var/tmp/portage
                mounted="true"
}

compile() {
        einfo "running emerge ${*}"
                emerge ${*}
}

unmount() {
        ebegin "unmounting tmpfs"
                umount -f /var/tmp/portage
        eend $?
}

ebegin "Mounting $MEMSIZE of memory to /var/tmp/portage"
        if [ -z "$(pgrep -f /usr/bin/emerge)" ];then
                if [ -z "$(mount | grep /var/tmp/portage)" ];then
                     mounttmpfs
                else
                     eerror "tmpfs already mounted!"
                     exit 0
                fi
        else
                eerror "emerge already running!"
                exit 0
        fi
eend $?

# the next line would change the cpu-governour, if available, to the highest frequency
#[ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ] && echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# run emerge
compile $@

# unmount tmpfs
$mounted && umount /var/tmp/portage

# and set the scheduler back to "ondemand"
#[ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ] && echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
